import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import appstyles from '../styles/app.module.css';
import { Navigation } from '../components/Navigation';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const links = [
  { href: '/', label: 'Home', icon: 'H' },
  { href: '/dashboard', label: 'Dashboard', icon: 'D' },
  { href: '/settings', label: 'Setting', icon: 'S' },
];

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={appstyles.gridContainer}>
          <Navigation links={links} />
          {children}
        </main>
      </body>
    </html>
  );
}
